### ISSUE TITLE
pandas is not required

### ISSUE THREAD

**Issue by finswimmer** [JuBiotech/robotools#71]
Hello,

thanks a lot for this awesome package!

In the requirements `pandas` is listed, but it seems to me that it is not used anywhere, is it?

Are you interested in using poetry for dependency management? This is quite useful to manage dependency only used during development e.g. pytest, mypy, pre-commit. If so I could provide a PR for it, that also fixes the unnecessary dependency to pandas as well.

fin swimmer

**Comment by michaelosthege** [comment]
closed by #74
